const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// 1. Read config.json
const configPath = path.join(__dirname, 'config.json');
let config = {
  apiBaseUrl: "http://localhost:4000/api",
  frontendUrl: "http://localhost:3000"
};

if (fs.existsSync(configPath)) {
  try {
    config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch (e) {
    console.error('[BUILD] Error parsing config.json, using defaults.', e);
  }
}

const apiBaseUrl = config.apiBaseUrl.replace(/\/$/, '');
const frontendUrl = config.frontendUrl.replace(/\/$/, '');

// 2. Generate src/config.ts
const configTsContent = `// Automatically generated by build.js. Do not edit directly.
export const API_BASE_URL = '${apiBaseUrl}';
export const FRONTEND_URL = '${frontendUrl}';
`;
fs.writeFileSync(path.join(__dirname, 'src', 'config.ts'), configTsContent, 'utf8');
console.log('[BUILD] Generated src/config.ts successfully.');

// 3. Update manifest.json host_permissions and content_scripts matches
const manifestPath = path.join(__dirname, 'manifest.json');
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  const apiUrlObj = new URL(apiBaseUrl);
  const apiHostPermission = `${apiUrlObj.protocol}//${apiUrlObj.host}/*`;
  
  const frontendUrlObj = new URL(frontendUrl);
  const frontendHostPermission = `${frontendUrlObj.protocol}//${frontendUrlObj.host}/*`;

  // Update host_permissions - only grant mail.google.com and API host permissions
  manifest.host_permissions = [
    "https://mail.google.com/*",
    apiHostPermission
  ];

  // Update content scripts to match dashboard URL so we can inject extension detection attribute
  manifest.content_scripts = [
    {
      "matches": [
        "https://mail.google.com/*",
        frontendHostPermission
      ],
      "js": [
        "dist/content.js"
      ],
      "run_at": "document_end"
    }
  ];

  // Build-time validation: fail if required permissions are missing
  const expectedHostPerms = ["https://mail.google.com/*", apiHostPermission];
  for (const hp of expectedHostPerms) {
    if (!manifest.host_permissions.includes(hp)) {
      console.error(`[BUILD_ERROR] Missing expected host permission: ${hp}`);
      process.exit(1);
    }
  }

  const expectedMatches = ["https://mail.google.com/*", frontendHostPermission];
  for (const match of expectedMatches) {
    if (!manifest.content_scripts[0].matches.includes(match)) {
      console.error(`[BUILD_ERROR] Missing expected content script match: ${match}`);
      process.exit(1);
    }
  }

  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
  console.log('[BUILD] Updated and validated manifest.json permissions.');
} else {
  console.error('[BUILD] manifest.json not found!');
  process.exit(1);
}

// 4. Run TypeScript compilation
console.log('[BUILD] Running tsc...');
try {
  execSync('npx tsc', { cwd: __dirname, stdio: 'inherit' });
  console.log('[BUILD] TypeScript compilation complete.');
} catch (e) {
  console.error('[BUILD] TypeScript compilation failed.', e.message);
  process.exit(1);
}

console.log('[BUILD] Extension built successfully!');
